INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('java.lang.NullPointerException');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.appsportfolio.jsf.architecture.beans.ResourceGroupConfigurationBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.async.mdb.RePriceAsyncTasksConsumerMDB]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.common.policyframework.engine.PolicyEngineLogger]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.async.mdb.VdcSyncConsumerMDB]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.appsportfolio.jsf.architecture.beans.ResourceGroupBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.thymeleaf.TemplateEngine]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.core.services.email.ApplicationEmailMDB]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.softlayer.server.pricing.PricingEngineHandler]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.appsportfolio.jsf.architecture.actions.AddResourceGroupHandler]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.common.util.AbstractRestBase]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.appsportfolio.jsf.architecture.beans.ResourceGroupConfigurationBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.appsportfolio.jsf.architecture.beans.ResourceGroupDetailsBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('javax.ejb.EJBException: com.gravitant.bts.bms.exception.GraException: Display Message:Transaction commit failed');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('Failed in refresh: : java.lang.NullPointerException');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bts.bms.exception.GraBmsRuntimeException]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.billing.service.estimation.BillEstimationService]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR [stderr] (EJB default');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.sync.impl.errors.NoTemplateErrorProcessor]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bts.bms.exception.GraBmsRuntimeException]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.orders.broker.controller.BrokerOrderController]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.thymeleaf.TemplateEngine]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.engine.PricingBase]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.common.jsf.core.beans.ActivityLoggerTableListBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.common.policyframework.policyProvider.bootScript.BootScriptConsumer]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.async.mdb.AsyncTasksConsumerMDB]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.appsportfolio.jsf.architecture.beans.StorageAccountBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.common.planning.util.BmsProvisioningHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('javax.faces.FacesException: Cannot add the same component twice: architectureMainContentForm:menuBarArch');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('java.lang.Exception: Invalid Context Code - APP');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR  [com.arjuna.ats.arjuna]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('java.lang.Exception: Invalid Context Code - VDC');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR [com.gravitant.azure.client.service.AzureComputeService]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR [com.gravitant.cloud.adapters.provision.providers.AmazonEC2]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.common.planning.util.BmsOrderConsolidationHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.azure.client.service.AzureComputeService]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.picketlink.identity.federation]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bts.bms.transaction.BTSTransaction]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('Failure in initialisation: java.lang.NullPointerException');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR [com.gravitant.cloud.userapp.proxy.impl.ejb.WhiteLabelInfoProxyEjb]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR [org.apache.catalina.core.ContainerBase.[jboss.web]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR [org.jboss.naming.remote.protocol.v1.RemoteNamingStoreV1]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.sync.util.BmsVdcSyncHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR [com.gravitant.cloud.core.jsf.helpers.CmwSecurity]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.hibernate.engine.jdbc.spi.SqlExceptionHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('java.lang.IndexOutOfBoundsException');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.providerservices.proxy.impl.ejb.ProviderManagementProxyEjb]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.appsportfolio.jsf.architecture.actions.AddResourceGroupHandler]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.common.proxy.impl.ejb.ProviderAccountProxyEjb]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('Failed to scanAndUpdateResources data: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bts.bms.util.BmsBaseFindersUtil]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_OUTSIDE: Some work is done outside global transaction');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('Could not initialize storage provider proxy');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bts.bms.topology.Topology]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.hibernate.engine.jdbc.spi.SqlExceptionHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.azure.client.service.AzureComputeService]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('Error while getting Work Flow Service Task OrderId for asyncTaskId');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.azure.client.service.AzureComputeService]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.sync.impl.DeleteVMResultProcessor]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.sync.util.BmsVdcSyncHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bts.bms.topology.Topology]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.timer.beans.TimerBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.jboss.as.ejb3.invocation]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.hibernate.engine.jdbc.spi.SqlExceptionHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.azure.adapter.provider.AzureProvider]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.azure.client.service.AzureComputeService]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.bms.common.planning.util.BmsWorkflowHelper]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.appsportfolio.jsf.architecture.beans.AddResourceGroupBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.common.proxy.impl.ejb.ProviderAccountProxyEjb]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[com.gravitant.cloud.core.jsf.beans.ExceptionDisplayContentBean]');
INSERT INTO ErrorsDict_errorsdict(Error_name) VALUES ('[org.jboss.naming.remote.protocol.v1.RemoteNamingStoreV1]');
